name: 'Export API Specs from MuleSoft Anypoint Exchange'
description: 'Downloads OpenAPI specifications, categories, tags, and documentation from MuleSoft Anypoint Exchange'
author: 'Your Organization'

inputs:
  exchange-url:
    description: 'MuleSoft Anypoint Exchange URL'
    required: false
    default: 'https://anypoint.mulesoft.com'
  
  organization-id:
    description: 'MuleSoft Organization ID'
    required: true
  
  asset-id:
    description: 'Asset ID to download (optional - if not provided, downloads all assets)'
    required: false
  
  output-directory:
    description: 'Directory to store downloaded files'
    required: false
    default: 'api-specs'
  
  include-metadata:
    description: 'Whether to download categories and tags metadata'
    required: false
    default: 'true'
  
  repository-destination:
    description: 'Directory in the repository where files should be moved (relative to repository root)'
    required: false
    default: '.'
  
  documentation-path:
    description: 'Custom subdirectory path for documentation files (will be created under documentation/ folder)'
    required: false
    default: ''
  
  categories-path:
    description: 'Custom path for categories.json file within the repository'
    required: false
    default: '.'
  
  specs-path:
    description: 'Custom path for OpenAPI specification files within the repository'
    required: false
    default: '.'

outputs:
  specs-count:
    description: 'Number of API specifications downloaded'
  
  docs-count:
    description: 'Number of documentation items downloaded'
  
  categories-count:
    description: 'Number of categories extracted'
  
  output-path:
    description: 'Path where files were downloaded'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install requests pyyaml markdownify python-dotenv
    
    - name: Download API specs from Anypoint Exchange
      shell: bash
      env:
        CLIENT_ID: ${{ env.CLIENT_ID }}
        CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
        EXCHANGE_URL: ${{ inputs.exchange-url }}
        ORGANIZATION_ID: ${{ inputs.organization-id }}
        ASSET_ID: ${{ inputs.asset-id }}
        OUTPUT_DIR: ${{ inputs.output-directory }}
        INCLUDE_DOCS: 'true'
        INCLUDE_METADATA: ${{ inputs.include-metadata }}
      run: |
        python ${{ github.action_path }}/download_specs.py
    
    - name: Move files to repository destination
      shell: bash
      run: |
        # Set documentation path, handling empty or '.' values
        DOC_PATH="${{ inputs.documentation-path }}"
        if [ "$DOC_PATH" = "." ] || [ -z "$DOC_PATH" ]; then
          DOC_FULL_PATH="${{ inputs.repository-destination }}/documentation"
        else
          DOC_FULL_PATH="${{ inputs.repository-destination }}/documentation/$DOC_PATH"
        fi
        
        # Set categories path, handling empty or '.' values
        CAT_PATH="${{ inputs.categories-path }}"
        if [ "$CAT_PATH" = "." ] || [ -z "$CAT_PATH" ]; then
          CAT_FULL_PATH="${{ inputs.repository-destination }}"
        else
          CAT_FULL_PATH="${{ inputs.repository-destination }}/$CAT_PATH"
        fi
        
        # Set specs path, handling empty or '.' values
        SPECS_PATH="${{ inputs.specs-path }}"
        if [ "$SPECS_PATH" = "." ] || [ -z "$SPECS_PATH" ]; then
          SPECS_FULL_PATH="${{ inputs.repository-destination }}"
        else
          SPECS_FULL_PATH="${{ inputs.repository-destination }}/$SPECS_PATH"
        fi
        
        # Create directories
        mkdir -p "$DOC_FULL_PATH"
        mkdir -p "$CAT_FULL_PATH"
        mkdir -p "$SPECS_FULL_PATH"
        
        if [ -d "${{ inputs.output-directory }}" ]; then
          # Move extracted OAS files (YAML/JSON from extracted directories)
          find ${{ inputs.output-directory }} -path "*_extracted/*" \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) -exec cp {} "$SPECS_FULL_PATH"/ \;
          
          # Move markdown files to documentation folder
          find ${{ inputs.output-directory }} -name "*.md" -exec cp {} "$DOC_FULL_PATH"/ \;
          
          # Move categories.json to specified path
          find ${{ inputs.output-directory }} -name "categories.json" -exec cp {} "$CAT_FULL_PATH"/ \;
        fi
    
    - name: Commit and push files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ inputs.repository-destination }}
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update API specs, categories, and documentation from MuleSoft Anypoint Exchange"
          git push
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mulesoft-api-specs  
        path: ${{ inputs.repository-destination }}
        retention-days: 30

branding:
  icon: 'download'
  color: 'blue'